[type.po]
extend-glob = ["*.csr"]
check-file = false

[default.extend-words]
# Additionals is important for WebRTC
additionals = "additionals"
# STAP-A for WebRTC
stap = "stap"
# MIS value
mis = "mis"
# datas is used a lot for plural.
datas = "datas"
# 2nd for second
2nd = "2nd"
